### ISSUE TITLE
Search-and-replace

### ISSUE THREAD

**Issue by tronsmit** [vesta-webtrees-2-custom-modules/vesta_classic_laf#49]
Logged in I use search and replace from menu

With vesta modules enabled the header is gone, with vesta modules disabled I see full header and menu options

(In both cases I see form for search and replace)

I only use common and classic laf

**Comment by ric2016** [comment]
This is a (perhaps unintended, I'll have to think about this) side-effect of the configuration option "Use compact layout" which omits header and footer for all edit dialogs.

I.e. for now you can change this behavior via the module configuration. I'll have to decide whether to exclude this particular dialog from the option. It is indeed a bit jarring because the other searches are displayed differently (because they do not actually change anything, and therefore do not fall under 'edit dialogs').

**Comment by ric2016** [comment]
Fixed in 2.0.15.2.0 (i.e. now always displayed with header ands footer).
