### ISSUE TITLE
GVExport preferences partially behind the webtrees menu

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_classic_laf#80]
When using the GVExport module by @[tillsc](https://github.com/tillsc/GVExport) (for webtrees 2.0.x) or by @[Neriderc](https://github.com/Neriderc/GVExport) (for webtrees 2.1.x) and the Rural theme, it is not possible to close the Diagram preferences because the close button is behind the webtrees menu.

This problem occurs only with the [Vesta Classic Look & Feel module](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf).

See also: [https://github.com/jon48/webtrees-theme-rural/issues/42](https://github.com/jon48/webtrees-theme-rural/issues/42)

**Comment by jon48** [comment]
@TheDutchJewel  Thanks for identifying this conflict.

Having installed the Classic Look & Feel module, I can indeed reproduce the display issue. The problem actually "exists" on all themes, but headers on the standard themes are less than 200px high (which is where the sidebar is set to start, as hardcoded in the GVExport CSS - `.sidebar { top: 200px }`), so this is only exhibited on the Rural theme because of the larger header.

Where it conflicts with the Classic L&F module is because the latter sets `header { z-index: 1010; }`, whereas GVExport sets `header { z-index: 1; }` for the preferences block., it displays therefore under the whole header (including the menu).

To be fair, on this specific issue, I feel that this should be amended in the GVExport module itself. Setting such a low value for z-index for something which is always on top is going to cause issues. For instance, Boostrap itself uses 1000 for its drop-down menus, which therefore appears on top of the preferences. This probably aims to be at a similar level as modal windows (about 1050).

This however raised another question to me. I am not familiar with the Classic L&F module, and how it is supposed to interact with webtrees, but I was surprised to discover it is adding a full set of rather generic CSS rules in addition to my theme (after my CSS actually, so it takes precedence over my theme). As a theme author, this creates a rather uncomfortable situation as I am not expecting another "theme-like" module to add generic CSS rules that can change structural aspects of the page, which may not be compatible with the intent of the main theme.
If my understanding is correct, the main intent of the L&F module was initially to restore some displays of webtrees 1.7, but I feel that it should target only the standard themes, and not custom themes, which may have taken different design decisions for which the hacks are not necessary (or even conflictual).

**Comment by TheDutchJewel** [comment]
@jon48 Thanks for your reaction!

Changing `z-index `from `1` to `1050` in the GVExport module works fine.

I added for both modules a pull request with this little change.

**Comment by ric2016** [comment]
> I feel that it should target only the standard themes, and not custom themes, which may have taken different design decisions for which the hacks are not necessary (or even conflictual).

This seems like a reasonable suggestion for some 'theme-like' aspects of the Vesta module. Most adjustments are theme-independent though. I'll have to investigate this further. I'll also check whether the z-index adjustment is still required in webtrees 2.1.

Note in general that additional css is always possible (there is even a specific non-Vesta module for that), so custom themes should expect this to some extent.

**Comment by ric2016** [comment]
z-Index adjustment seems to be no longer required in webtrees 2.1. Removed in latest release.
