### ISSUE TITLE
Compatibility with theme ArgonLight

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_classic_laf#95]
There is a compatibility problem: see https://github.com/06Games/Webtrees-ArgonLight/issues/3

**Comment by ric2016** [comment]
I'll likely be able to handle this with an additional switch, similar to how the layout for the JustLight module is preserved ([starting here](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/blob/410d2cb15f0f147b156d1b83cac84ff0d7f0f485/ClassicLAFModule.php#L131)).

**Comment by hartenthaler** [comment]
hmmm... on my webtrees test server ArgonLight and Vesta classic_laf are working perfectly together.

**Comment by ric2016** [comment]
Vesta only adjusts the layout if the option "Edit dialogs > Use compact layout" is enabled - Maybe you do not use that?

**Comment by hartenthaler** [comment]
"Use compact layout" is enabled in the test and in the productive system.

**Comment by hartenthaler** [comment]
I have now disabled "Use compact layout" in the productive system https://ahnen.hartenthaler.eu/ and the issue is still there.

**Comment by ric2016** [comment]
Note that there are two settings: You have disabled "Individual page > Use compact layout", which isn't relevant for this. The setting which causes the module to use a custom layout view is "Edit dialogs > Use compact layout".

Anyway, I'll resolve this by disabling the latter for most non-standard custom modules, such as this one, because they may adjust the layout differently anyway.

**Comment by ric2016** [comment]
Fixed as outlined in 2.1.7.0.2.
